server:
  port: 8081
spring:
  rabbitmq:
    host: 39.105.189.141
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  application:
    name: comment
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://39.100.249.198:3306/test?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource